project_id = "yyzrwjocniepskofoehu"

[auth]
site_url = "https://horalix.com"
additional_redirect_urls = ["https://horalix.com", "https://www.horalix.com"]

[functions.send-contact-notification]
verify_jwt = false

[functions.create-admin-user]
verify_jwt = false

[functions.delete-user-account]
verify_jwt = true

[functions.send-status-notification]
verify_jwt = false
